# Generated by Django 5.2 on 2025-05-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="posts",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="likes",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of likes for the post"
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="blog_posts", to="blog.tag"
            ),
        ),
    ]
