# Generated by Django 5.2 on 2025-05-30 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_tag_posts_blogpost_likes_blogpost_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="likes",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="tags",
        ),
        migrations.AddField(
            model_name="tag",
            name="posts",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to="blog.blogpost"
            ),
        ),
    ]
